name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4']
        os: [ubuntu-24.04]
        include:
          - php: '8.4'
            os: ubuntu-24.04-arm
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, gd, mbstring
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/phpunit
